### ISSUE TITLE
creation new scenario with driver is missing manadatory options

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/molecule-openstack#3]
At this moment these two options are missing from molecule.yml when creating a new scenario:
```
---
dependency:
  name: galaxy
driver:
  name: openstack
platforms:
  - name: instance
    image: foo  # <-- missing
    flavor: bar  # <-- missing
provisioner:
  name: ansible
verifier:
  name: ansible
```

The idea is to find a way to have something created there, something that is likely to work for the user.
